name: Lint

# Trigger the workflow on push or pull request, but only for the
# master branch
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/ci.yml'
      - 'appveyor.yml'
      - '**/CHANGELOG.md'
      - '**/FUNDING.md'
      - '**/LICENSE'
      - '**/README.md'
      - '**/stack.yaml'
      - '**/*.cabal'
  push:
    paths-ignore:
      - '.github/workflows/ci.yml'
      - 'appveyor.yml'
      - '**/CHANGELOG.md'
      - '**/FUNDING.md'
      - '**/LICENSE'
      - '**/README.md'
      - '**/stack.yaml'
      - '**/*.cabal'

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up HLint
        uses: haskell-actions/hlint-setup@v2

      - name: Run HLint
        uses: haskell-actions/hlint-run@v2
        with:
          path: '.'
          fail-on: warning
